import { DepartmentInfo, CategoryInfo, SchoolDepartment, DocumentCategory, DocumentPriority, DocumentStatus, SchoolDocument } from './types';

export const DEPARTMENTS: Record<SchoolDepartment, DepartmentInfo> = {
  academic: {
    id: 'academic',
    labelTh: 'กลุ่มบริหารวิชาการ',
    labelEn: 'Academic Affairs',
    color: 'text-blue-600',
    badgeBg: 'bg-blue-100 text-blue-950 border-2 border-black font-bold',
    borderColor: 'border-black',
    icon: 'GraduationCap',
  },
  administration: {
    id: 'administration',
    labelTh: 'กลุ่มบริหารทั่วไป / สารบรรณ',
    labelEn: 'General Administration & Secretariat',
    color: 'text-black',
    badgeBg: 'bg-neutral-100 text-black border-2 border-black font-bold',
    borderColor: 'border-black',
    icon: 'Building2',
  },
  personnel: {
    id: 'personnel',
    labelTh: 'กลุ่มบริหารงานบุคคล',
    labelEn: 'Human Resources & Personnel',
    color: 'text-purple-600',
    badgeBg: 'bg-purple-100 text-purple-950 border-2 border-black font-bold',
    borderColor: 'border-black',
    icon: 'Users',
  },
  budget: {
    id: 'budget',
    labelTh: 'กลุ่มแผนงานและงบประมาณ',
    labelEn: 'Planning & Finance / Budget',
    color: 'text-amber-600',
    badgeBg: 'bg-yellow-300 text-black border-2 border-black font-bold',
    borderColor: 'border-black',
    icon: 'Coins',
  },
  student_affairs: {
    id: 'student_affairs',
    labelTh: 'กลุ่มบริหารกิจการนักเรียน',
    labelEn: 'Student Affairs',
    color: 'text-rose-600',
    badgeBg: 'bg-rose-100 text-rose-950 border-2 border-black font-bold',
    borderColor: 'border-black',
    icon: 'ShieldCheck',
  },
};

export const CATEGORIES: CategoryInfo[] = [
  { id: 'order', department: 'administration', labelTh: 'คำสั่งโรงเรียน', labelEn: 'School Order', codePrefix: 'คส.' },
  { id: 'official_memo', department: 'administration', labelTh: 'หนังสือราชการ / บันทึกข้อความ', labelEn: 'Official Circular / Memo', codePrefix: 'ศธ.' },
  { id: 'announcement', department: 'administration', labelTh: 'ประกาศโรงเรียน', labelEn: 'School Announcement', codePrefix: 'ปก.' },
  { id: 'lesson_plan', department: 'academic', labelTh: 'แผนการจัดการเรียนรู้', labelEn: 'Lesson Plan', codePrefix: 'ผส.' },
  { id: 'curriculum', department: 'academic', labelTh: 'หลักสูตรสถานศึกษา / โครงการสอน', labelEn: 'Curriculum & Syllabus', codePrefix: 'ลส.' },
  { id: 'student_record', department: 'academic', labelTh: 'ผลสัมฤทธิ์ / ปพ. / ทะเบียนวัดผล', labelEn: 'Student Record & Assessment', codePrefix: 'ปพ.' },
  { id: 'portfolio', department: 'personnel', labelTh: 'แฟ้มสะสมงานครู / ข้อตกลง PA', labelEn: 'Teacher Portfolio / PA', codePrefix: 'PA.' },
  { id: 'training', department: 'personnel', labelTh: 'วุฒิบัตร / บันทึกการอบรมพัฒนา', labelEn: 'Certificate & Training', codePrefix: 'อบ.' },
  { id: 'procurement', department: 'budget', labelTh: 'เอกสารจัดซื้อจัดจ้าง / พัสดุ', labelEn: 'Procurement & Inventory', codePrefix: 'พด.' },
  { id: 'budget_plan', department: 'budget', labelTh: 'แผนปฏิบัติการประจำปี / โครงการ', labelEn: 'Annual Action Plan & Budget', codePrefix: 'ผง.' },
  { id: 'meeting_minutes', department: 'administration', labelTh: 'รายงานการประชุม', labelEn: 'Meeting Minutes', codePrefix: 'รป.' },
  { id: 'general', department: 'student_affairs', labelTh: 'เอกสารทั่วไป / กิจกรรมนักเรียน', labelEn: 'General & Activities', codePrefix: 'ทป.' },
];

export const PRIORITIES: Record<DocumentPriority, { labelTh: string; labelEn: string; color: string; badge: string }> = {
  normal: {
    labelTh: 'ปกติ',
    labelEn: 'Normal',
    color: 'text-black',
    badge: 'bg-white text-black border-2 border-black font-bold',
  },
  urgent: {
    labelTh: 'ด่วน',
    labelEn: 'Urgent',
    color: 'text-blue-600',
    badge: 'bg-blue-600 text-white border-2 border-black font-black uppercase',
  },
  urgent_high: {
    labelTh: 'ด่วนมาก',
    labelEn: 'Very Urgent',
    color: 'text-amber-600',
    badge: 'bg-yellow-400 text-black border-2 border-black font-black uppercase',
  },
  urgent_top: {
    labelTh: 'ด่วนที่สุด',
    labelEn: 'Top Urgent',
    color: 'text-rose-600',
    badge: 'bg-rose-600 text-white border-2 border-black font-black uppercase tracking-wider',
  },
};

export const STATUSES: Record<DocumentStatus, { labelTh: string; labelEn: string; badge: string; dot: string }> = {
  draft: {
    labelTh: 'ร่างเอกสาร',
    labelEn: 'Draft',
    badge: 'bg-neutral-200 text-black border-2 border-black font-bold',
    dot: 'bg-neutral-600',
  },
  pending: {
    labelTh: 'รอตรวจสอบ/ลงนาม',
    labelEn: 'Pending Review',
    badge: 'bg-yellow-300 text-black border-2 border-black font-bold',
    dot: 'bg-amber-600',
  },
  approved: {
    labelTh: 'ลงนามอนุมัติแล้ว',
    labelEn: 'Approved',
    badge: 'bg-black text-white border-2 border-black font-bold',
    dot: 'bg-white',
  },
  published: {
    labelTh: 'ประกาศใช้ / เผยแพร่',
    labelEn: 'Published',
    badge: 'bg-blue-600 text-white border-2 border-black font-bold',
    dot: 'bg-white',
  },
  archived: {
    labelTh: 'จัดเก็บเข้าแฟ้มถาวร',
    labelEn: 'Archived',
    badge: 'bg-neutral-100 text-black border-2 border-black font-bold',
    dot: 'bg-black',
  },
};

export const SAMPLE_DOCUMENTS: SchoolDocument[] = [
  {
    id: 'doc-001',
    code: 'ศธ 04225/ว 118',
    title: 'คำสั่งแต่งตั้งคณะกรรมการจัดทำแผนปฏิบัติการประจำปีการศึกษา 2568',
    department: 'budget',
    category: 'order',
    priority: 'urgent',
    status: 'approved',
    academicYear: '2568',
    semester: '1',
    issuer: 'กลุ่มแผนงานและงบประมาณ',
    signer: 'นายสมชาย ประเสริฐวิทย์ (ผู้อำนวยการโรงเรียน)',
    docDate: '2026-05-10',
    registeredDate: '2026-05-11',
    summary: 'แต่งตั้งคณะทำงานบุคลากรครูและผู้บริหารเพื่อร่วมกันยกร่างและกำหนดทิศทางแผนงบประมาณพัฒนาสถานศึกษา ประจำปีงบประมาณ 2568',
    tags: ['แผนปฏิบัติการ', 'คำสั่งแต่งตั้ง', 'งบประมาณ 2568'],
    driveAttachment: {
      fileId: 'mock-drive-01',
      name: 'Order_Committee_AnnualPlan_2568.pdf',
      mimeType: 'application/pdf',
      size: 1485760,
      webViewLink: 'https://drive.google.com',
      uploadedAt: '2026-05-11T09:30:00Z',
    },
    createdAt: '2026-05-11T09:30:00Z',
    updatedAt: '2026-05-11T09:30:00Z',
  },
  {
    id: 'doc-002',
    code: 'วช 02/2568',
    title: 'แผนการจัดการเรียนรู้บูรณาการ Active Learning รายวิชาวิทยาศาสตร์และเทคโนโลยี ชั้น ม.3',
    department: 'academic',
    category: 'lesson_plan',
    priority: 'normal',
    status: 'approved',
    academicYear: '2568',
    semester: '1',
    issuer: 'ครูณภัทร สุขสมบูรณ์ (กลุ่มสาระวิทยาศาสตร์)',
    signer: 'นางวิภาวรรณ ชัยเจริญ (หัวหน้าฝ่ายวิชาการ)',
    docDate: '2026-05-18',
    registeredDate: '2026-05-19',
    summary: 'แผนการสอนเน้นการทดลองและแก้ปัญหาจริง จำนวน 40 คาบเรียน พร้อมเกณฑ์การประเมินรูบริกส์ (Rubric Assessment)',
    tags: ['ม.3', 'Active Learning', 'วิทยาศาสตร์', 'แผนการสอน'],
    driveAttachment: {
      fileId: 'mock-drive-02',
      name: 'LessonPlan_Science_M3_ActiveLearning.pdf',
      mimeType: 'application/pdf',
      size: 3245100,
      webViewLink: 'https://drive.google.com',
      uploadedAt: '2026-05-19T14:20:00Z',
    },
    createdAt: '2026-05-19T14:20:00Z',
    updatedAt: '2026-05-19T14:20:00Z',
  },
  {
    id: 'doc-003',
    code: 'ศธ 04225/บ 45',
    title: 'บันทึกข้อความขออนุมัติโครงการค่ายอบรมคุณธรรมจริยธรรมนักเรียน ม.1 และ ม.4',
    department: 'student_affairs',
    category: 'official_memo',
    priority: 'urgent_high',
    status: 'pending',
    academicYear: '2568',
    semester: '1',
    issuer: 'ครูศิริพร บุญมั่น (งานกิจการนักเรียน)',
    signer: 'นายสมชาย ประเสริฐวิทย์ (ผู้อำนวยการโรงเรียน)',
    docDate: '2026-06-02',
    registeredDate: '2026-06-03',
    summary: 'ขออนุมัติการดำเนินโครงการค่ายปฐมนิเทศคุณธรรม ประจำปีการศึกษา 2568 ณ หอประชุมเฉลิมพระเกียรติ พร้อมรายละเอียดค่าใช้จ่าย',
    tags: ['กิจการนักเรียน', 'ค่ายคุณธรรม', 'ม.1', 'ม.4'],
    createdAt: '2026-06-03T10:15:00Z',
    updatedAt: '2026-06-03T10:15:00Z',
  },
  {
    id: 'doc-004',
    code: 'PA-2567-08',
    title: 'แบบข้อตกลงในการพัฒนางาน (PA) สำหรับข้าราชการครูและบุคลากรทางการศึกษา ตำแหน่งครูชำนาญการ',
    department: 'personnel',
    category: 'portfolio',
    priority: 'normal',
    status: 'approved',
    academicYear: '2567',
    semester: 'both',
    issuer: 'ครูเอกชัย สุทธิพันธุ์ (ครูกลุ่มสาระคณิตศาสตร์)',
    signer: 'นายสมชาย ประเสริฐวิทย์ (ผู้อำนวยการโรงเรียน)',
    docDate: '2025-10-01',
    registeredDate: '2025-10-02',
    summary: 'เอกสารข้อตกลง PA ปีงบประมาณ 2567 แสดงเป้าหมายการจัดการเรียนรู้ การแก้ปัญหาผลสัมฤทธิ์คณิตศาสตร์ และประเด็นท้าทาย',
    tags: ['PA', 'วPA', 'ประเมินครู', 'คณิตศาสตร์'],
    driveAttachment: {
      fileId: 'mock-drive-03',
      name: 'Agreement_PA_Math_Teacher2567.pdf',
      mimeType: 'application/pdf',
      size: 2150000,
      webViewLink: 'https://drive.google.com',
      uploadedAt: '2025-10-02T11:00:00Z',
    },
    createdAt: '2025-10-02T11:00:00Z',
    updatedAt: '2025-10-02T11:00:00Z',
  },
  {
    id: 'doc-005',
    code: 'พด 15/2568',
    title: 'รายงานขอซื้อขอจ้างวัสดุอุปกรณ์ห้องปฏิบัติการคอมพิวเตอร์และสื่อสารสนเทศ',
    department: 'budget',
    category: 'procurement',
    priority: 'urgent_top',
    status: 'pending',
    academicYear: '2568',
    semester: '1',
    issuer: 'นายธนาธิป เก่งวิทย์ (หัวหน้างานพัสดุและยานพาหนะ)',
    signer: 'นายสมชาย ประเสริฐวิทย์ (ผู้อำนวยการโรงเรียน)',
    docDate: '2026-06-15',
    registeredDate: '2026-06-15',
    summary: 'ขอความเห็นชอบจัดซื้อสายสัญญาณ LAN อุปกรณ์กระจายสัญญาณ Wi-Fi 6 และชุดบำรุงรักษาคอมพิวเตอร์เพื่อเปิดภาคเรียน',
    tags: ['พัสดุ', 'จัดซื้อจัดจ้าง', 'ห้องคอมพิวเตอร์', 'งบประมาณ'],
    createdAt: '2026-06-15T08:45:00Z',
    updatedAt: '2026-06-15T08:45:00Z',
  },
  {
    id: 'doc-006',
    code: 'ปก 09/2568',
    title: 'ประกาศโรงเรียน เรื่อง มาตรการความปลอดภัยและสุขอนามัยในสถานศึกษา ประจำภาคเรียนที่ 1/2568',
    department: 'administration',
    category: 'announcement',
    priority: 'urgent',
    status: 'published',
    academicYear: '2568',
    semester: '1',
    issuer: 'กลุ่มบริหารทั่วไป',
    signer: 'นายสมชาย ประเสริฐวิทย์ (ผู้อำนวยการโรงเรียน)',
    docDate: '2026-05-15',
    registeredDate: '2026-05-15',
    summary: 'ประกาศแนวปฏิบัติสำหรับนักเรียน ครู และผู้ปกครองในการรักษาความปลอดภัย การสัญจรภายในโรงเรียน และการจัดการด้านสิ่งแวดล้อม',
    tags: ['ประกาศโรงเรียน', 'ความปลอดภัย', 'ภาคเรียนที่ 1'],
    driveAttachment: {
      fileId: 'mock-drive-04',
      name: 'Safety_Policy_Announcement_2026.pdf',
      mimeType: 'application/pdf',
      size: 980400,
      webViewLink: 'https://drive.google.com',
      uploadedAt: '2026-05-15T16:00:00Z',
    },
    createdAt: '2026-05-15T16:00:00Z',
    updatedAt: '2026-05-15T16:00:00Z',
  },
];
